stages:          # List of stages for jobs, and their order of execution
  - build
  - publish

build-job:       # Job to build the Docker image
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t "$DOCKER_USERNAME/todoapp:main" .
  only:
    - main

publish-job:     # Job to push the Docker image
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker push "$DOCKER_USERNAME/todoapp:main"
  only:
    - main
